FROM python:3.10
WORKDIR /usr/src/app
# Upgrade pip first
RUN pip install --no-cache-dir --upgrade pip
# Copy the requirements file first to leverage Docker cache
# Install dependencies
COPY . .
COPY env.yml /usr/src/app/env.yml
RUN pip install --no-cache-dir -r requirements.txt
RUN apt-get update && apt-get -y install cron
ADD mycronjob /etc/cron.d/main-cron
RUN chmod 0644 /etc/cron.d/main-cron
RUN touch /var/log/cron.log
CMD cron && tail -f /var/log/cron.log
